# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./client/build

jobs:
# Please do not rename this job
  build-project:
    name: build time-recording-system
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - name: Install server dependencies
        run: npm ci

      - name: Install client dependencies
        run: cd client && npm ci

      - name: Build client
        run: cd client && CI=false npm run build

      - name: Prepare .env file
        run: |
          touch .env
          echo GMAIL=${{ secrets.GMAIL }} >> .env
          echo MAIL=${{ secrets.MAIL }} >> .env
          echo MAIL_HOST=${{ secrets.MAIL_HOST }} >> .env
          echo MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} >> .env
          echo MAIL_PORT=${{ secrets.MAIL_PORT }} >> .env
          echo MAIL_SERVICE=${{ secrets.MAIL_SERVICE }} >> .env
          echo MONGODB_LOCAL=${{ secrets.MONGODB_LOCAL }} >> .env
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo RECAPTCHA=${{ secrets.RECAPTCHA }} >> .env
          echo RECAPTCHA_SECRET=${{ secrets.RECAPTCHA_SECRET }} >> .env
          echo SESS_SECRET=${{ secrets.SESS_SECRET }} >> .env
          echo DEPLOYMENT_PREFIX=${{ secrets.DEPLOYMENT_PREFIX }} >> .env
          echo TEST_DEPLOYMENT_PREFIX=${{ secrets.TEST_DEPLOYMENT_PREFIX }} >> .env
          echo ENVIRONMENT=${{ secrets.ENVIRONMENT }} >> .env

      - name: Run script
        env:
          PORT: 5555
          SESS_SECRET: ${{ secrets.SESS_SECRET }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_LOCAL: ${{ secrets.MONGODB_LOCAL }}
          GMAIL: ${{ secrets.GMAIL }}
          MAIL: ${{ secrets.MAIL }} 
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }} 
          MAIL_PORT: ${{ secrets.MAIL_PORT }} 
          MAIL_SERVICE: ${{ secrets.MAIL_SERVICE }} 
          RECAPTCHA: ${{ secrets.RECATCHA }} 
          RECAPTCHA_SECRET: ${{ secrets.RECAPTCHA_SECRET }} 
          DEPLOYMENT_PREFIX: ${{ secrets.DEPLOYMENT_PREFIX }}
          SITE_URL: ${{ inputs.site-url }}
        run: |
          cd client
          npm run build   

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: f7ff7190-b8b9-45c5-b114-a8668df39bdb
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/time-recording-system/config.yaml
          action: upload
