# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./

jobs:
# Please do not rename this job
  build-project:
    name: build time-recording-system
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - name: Build Node assets
        env:
          CI: true
          GMAIL: haeuszler.julia@gmail.com
          MAIL: julia@haeuszler.de
          MAIL_HOST: smtp.1und1.de
          MAIL_PASSWORD: Berlin2021!
          MAIL_PORT: 465
          MAIL_SERVICE: gmail
          MONGODB_LOCAL: mongodb://localhost/bhaeussler
          MONGODB_URI: mongodb+srv://adminbhaeussler:sHbfEvYDQQbret24@cluster0.jdcoi.mongodb.net/bhaeussler?retryWrites=true&w=majority
          PORT: 5555
          RECAPTCHA: 6LdCnccmAAAAAIkZPV5nV-ANWy7AwfELaLux_lyR
          RECAPTCHA_SECRET: 6LdCnccmAAAAAOtMeUML2bTAXohDgvddezbC8eLy
          SESS_SECRET: trs123
          SITE_URL: ${{ inputs.site-url }}
        run: npm ci

      - name: Run script
# uncomment the following lines if you want to add environment variables for this step
#        env:
#          MY_ENV_VAR: value-for-my-env-var
#          MY_SECRET_ENV_VAR: ${{ secrets.MY_SECRET }} # here you can find information how to create secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets
        run: |
          cd client && npm install && npm run build
          node ./bin/www

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 7c792156-732b-46a1-813c-d808b988184b
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/time-recording-system/config.yaml
          action: upload
